apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
type: Opaque
data:
  serverName: {{ .Values.config.serverName | b64enc }}
  adminUsername: {{ .Values.config.adminUsername | b64enc }}
  adminPassword: {{ .Values.config.adminPassword | b64enc }}
  maxRam: {{ .Values.config.maxRam | b64enc }}
---
{{- if .Values.sshConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sshConfig.secretName }}
type: Opaque
data:
  sshUsers: {{ .Values.sshConfig.username + ":" .Values.sshConfig.password + ":1000:data,server" }}
{{- end }}